In [2]:
import os
import pandas as pd
from PIL import Image, ImageDraw

In [6]:
filtered_species = pd.read_csv("data/Filtered_Train/filtered_annotations.csv")

In [12]:
filtered_species

,filename,width,height,class,xmin,ymin,xmax,ymax,Label
0,848617_jpg.rf.b6167489414b68fcfe2ccda38d24ac4a...,500.0,333.0,ahaetulla prasina,127.0,0.0,375.0,333.0,0
1,203459385_jpg.rf.73858ce8179c66e61c2203f4966e8...,500.0,375.0,bungarus caeruleus,144.0,48.0,332.0,325.0,2
2,178020213_jpg.rf.902a97ff37bebf466e6800e389762...,281.0,500.0,ptyas korros,0.0,161.0,281.0,347.0,10
3,AUG81008965_jpeg.rf.f10a9b8c28dba23257d0ee0594...,374.0,500.0,bungarus caeruleus,142.0,134.0,361.0,436.0,2
4,32814798_jpeg.rf.10944af1cd359dd50fca3e4518592...,243.0,500.0,ahaetulla prasina,60.0,129.0,179.0,325.0,0
...,...,...,...,...,...,...,...,...,...
6104,179205107_jpeg.rf.2370df92ee56a73f57d62f2507fd...,500.0,281.0,ptyas korros,89.0,23.0,360.0,272.0,10
6105,67339779_jpg.rf.32e82943c5b40705a822213cbc15aa...,500.0,333.0,ophiophagus hannah,207.0,13.0,304.0,320.0,8
6106,AUG8805242694_jpg.rf.01604ecea391d69924c14566a...,500.0,375.0,daboia russelii,34.0,50.0,472.0,342.0,5
6107,AUG133965490_jpeg.rf.9bed866d5b4f1bf3931ad6652...,417.0,500.0,bungarus caeruleus,132.0,124.0,361.0,376.0,2
6108,116497661_jpg.rf.69033f9ae5a7389f352ab3c9f6f9e...,500.0,224.0,ptyas korros,1.0,94.0,500.0,213.0,10

In [5]:
filtered_species.sample(5)

,filename,width,height,class,xmin,ymin,xmax,ymax,Label
5750,61933665_jpg.rf.21efc6eb0965c0d69c5b4e27ee5b95...,500.0,438.0,ptyas mucosa,67.0,60.0,424.0,389.0,11
3921,237352784_jpeg.rf.edd2b2e39b6f4341017c969b00db...,500.0,375.0,xenochrophis piscator,155.0,66.0,294.0,375.0,14
3553,217740490_jpg.rf.ff857196727645857e8762d64979d...,500.0,333.0,trimeresurus purpureomaculatus,117.0,102.0,299.0,254.0,13
4804,AUG19740312_jpeg.rf.ff9e7ff66e43c4a5a6265d3773...,374.0,500.0,daboia russelii,133.0,189.0,272.0,443.0,5
1914,168632214_jpeg.rf.cdb9da49ed6b322b50ffca1deb09...,500.0,500.0,ptyas korros,71.0,68.0,430.0,483.0,10

In [6]:
OUTPUT_DIR = "data/Processed_Train/images"

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("Folder created.")

Folder created.

In [35]:
# Input
IMAGE_FOLDER = "data/Filtered_Train"
OUTPUT_FOLDER = "data/Processed_Train/images"

In [37]:
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

processed_rows = []

PADDING = 0.15  # 10% padding

for _, row in filtered_species.iterrows():

    image_path = os.path.join(IMAGE_FOLDER, row["filename"])

    try:
        image = Image.open(image_path).convert("RGB")

        img_width, img_height = image.size

        xmin = int(row["xmin"])
        ymin = int(row["ymin"])
        xmax = int(row["xmax"])
        ymax = int(row["ymax"])

        box_width = xmax - xmin
        box_height = ymax - ymin

        pad_x = int(box_width * PADDING)
        pad_y = int(box_height * PADDING)

        xmin = max(0, xmin - pad_x)
        ymin = max(0, ymin - pad_y)
        xmax = min(img_width, xmax + pad_x)
        ymax = min(img_height, ymax + pad_y)

        cropped = image.crop((xmin, ymin, xmax, ymax))

        save_path = os.path.join(OUTPUT_FOLDER, row["filename"])
        cropped.save(save_path)

        processed_rows.append({
            "filename": row["filename"],
            "class": row["class"],
            "Label": row["Label"],
            "width": cropped.size[0],
            "height": cropped.size[1]
        })

    except Exception as e:
        print(f"Error: {row['filename']} -> {e}")

Error: 41909982_jpg.rf.47525d16a431a0c56efcfeabc504d2be.jpg -> cannot identify image file 'data/Filtered_Train\\41909982_jpg.rf.47525d16a431a0c56efcfeabc504d2be.jpg'

In [48]:
processed_annotations = pd.DataFrame(processed_rows)

processed_annotations.to_csv(
    "data/Processed_Train/processed_annotations.csv",
    index=False
)

print(f"Successfully processed {len(processed_annotations)} images.")

Successfully processed 6109 images.

In [49]:
processed_species = pd.read_csv("data/Processed_Train/processed_annotations.csv")

In [50]:
processed_species.sample(7)

,filename,class,Label,width,height
5071,219660494_jpg.rf.647655b4539c4234aac1be8e619cd...,psammodynastes pulverulentus,9,108,250
6039,161449844_jpg.rf.7e7bb2571ddab18e122ad4d7ccacf...,bungarus caeruleus,2,209,425
3182,112130025_jpeg.rf.294219a0baafb892b707332de35a...,dendrelaphis pictus,6,500,374
2657,54206638_jpeg.rf.e71cede4d4bc8c1baedceee21c3bb...,daboia russelii,5,279,281
4421,157289117_jpeg.rf.1f9ff199e30efe821a71fdcfcf6f...,daboia russelii,5,141,375
3715,121968659_jpeg.rf.a89bc8662e5b419c74a36948619f...,amphiesma stolatum,1,375,118
3436,83977004_jpg.rf.9bc22f7d2d1cff1c97de5b54376d25...,bungarus fasciatus,3,231,88

In [51]:
filtered_species.sample(7)

,filename,width,height,class,xmin,ymin,xmax,ymax,Label
4877,AUG233761657_jpeg.rf.ddfbcde1b7d5d320817fdf9d5...,500.0,281.0,bungarus caeruleus,58.0,111.0,500.0,193.0,2
5034,AUG212625418_jpeg.rf.0b287a37a2b4ac577e3b93be1...,500.0,309.0,daboia russelii,211.0,105.0,269.0,296.0,5
2720,244293460_jpeg.rf.9c40bfeed08d0c779220c1404e87...,375.0,500.0,naja naja,59.0,204.0,356.0,374.0,7
591,115059959_jpeg.rf.afa852b1c23e268e03833a3fc70f...,500.0,375.0,trimeresurus purpureomaculatus,121.0,0.0,437.0,318.0,13
1103,160687429_jpg.rf.b30cb77b56fc9bede4a6568ce57e6...,500.0,375.0,daboia russelii,76.0,0.0,382.0,313.0,5
4231,7476056_jpeg.rf.eaccab7b11f3534c1992d1a75f66d9...,500.0,373.0,ahaetulla prasina,63.0,0.0,399.0,331.0,0
2023,114294106_jpeg.rf.50a986970f670afb7ed4f3d977d0...,500.0,303.0,daboia russelii,219.0,0.0,369.0,303.0,5

In [53]:
print("Processed Images:", len(os.listdir("data/Processed_Train/images")))
print("CSV Rows:", len(processed_annotations))

Processed Images: 6109
CSV Rows: 6109

## Test data

In [26]:
import shutil

In [3]:
SOURCE_FOLDER = r"data/raw/test"
CSV_FILE = os.path.join(SOURCE_FOLDER, "_annotations.csv")
DEST_FOLDER = r"data/Processed_Images/Processed_test"

In [4]:
TARGET_SPECIES = {
    "naja naja",
    "bungarus caeruleus",
    "daboia russelii",
    "ptyas korros",
    "ophiophagus hannah",
    "bungarus fasciatus",
    "chrysopelea ornata",
    "ptyas mucosa",
    "xenochrophis piscator",
    "amphiesma stolatum",
    "dendrelaphis pictus",
    "ahaetulla prasina",
    "psammodynastes pulverulentus",
    "trimeresurus albolabris",
    "trimeresurus purpureomaculatus"
}

In [9]:
def analyze_test_data():
    process_test = pd.read_csv(CSV_FILE)
    
    # Normalize class names
    process_test["class"] = (
        process_test["class"]
            .str.strip()
            .str.lower()
    )
    # Handle synonyms
    process_test["class"] = process_test["class"].replace({
        "fowlea piscator": "xenochrophis piscator",
        "hebius stolatum": "amphiesma stolatum"
    })
    
    # Keep only target species
    filtered = process_test[process_test["class"].isin(TARGET_SPECIES)]

    # Remove duplicate filenames
    filtered = filtered.drop_duplicates(subset="filename")

    print(f"Images to copy: {len(filtered)}")
    
    
    # ===========================
    # COPY IMAGES
    # ===========================

    copied = 0
    skipped = 0
    missing = []

    os.makedirs(DEST_FOLDER, exist_ok=True)

    for filename in filtered["filename"].drop_duplicates().tolist():
        src = os.path.join(SOURCE_FOLDER, filename)
        dst = os.path.join(DEST_FOLDER, filename)

        if not os.path.exists(src):
            missing.append(filename)
            continue

        if os.path.exists(dst):
            skipped += 1
            continue

        shutil.copy2(src, dst)
        copied += 1
        
    print(f"\nCopied : {copied}")
    print(f"Skipped: {skipped}")
    print(f"Missing: {len(missing)}")

    if missing:
        print("\nMissing files:")
        for m in missing[:10]:
            print(m)
            
            
    # ===========================
    # SAVE FILTERED ANNOTATIONS
    # ===========================

    output_csv = os.path.join(DEST_FOLDER, "_annotations.csv")

    if os.path.exists(output_csv):
        print(f"{output_csv} already exists. Skipping save.")
    else:
        filtered.to_csv(output_csv, index=False)
        print(f"Saved {output_csv}")

In [5]:
TEST_CSV = pd.read_csv("data/Processed_Images/Processed_test\_annotations.csv")

classes = sorted(TEST_CSV["class"].unique()) # sorts them alphabetically.

class_to_idx = { # mapping integers {"cobra": 0, "python": 1, "viper": 2}
    cls: idx
    for idx, cls in enumerate(classes) # enumerate give pairs like (0, "cobra"), (1, "python")
}

idx_to_class = { # reverse {0: "cobra", 1: "python", 2: "viper"}
    idx: cls
    for cls, idx in class_to_idx.items() 
}

In [19]:
# creates a new column called Label
TEST_CSV["Label"] = TEST_CSV["class"].map(class_to_idx) #  applies the mapping to every value in the class column.
TEST_CSV.to_csv("data/Processed_Images/Processed_test_annotations.csv", index=False)
TEST_CSV

,filename,width,height,class,xmin,ymin,xmax,ymax,Label
0,100844199_jpeg.rf.8663ed9382261d114f4f924308aa...,375,500,chrysopelea ornata,105,0,313,356,4
1,102866274_jpg.rf.afe5c17f98908bcaeaf3462adf4bb...,500,364,dendrelaphis pictus,183,114,500,263,6
2,100844209_jpeg.rf.d4645d8cf8e9c0edfba87902a5a9...,375,500,chrysopelea ornata,126,84,218,372,4
3,100346824_jpeg.rf.37cdc3e14cb9f0f1a770d8bb470a...,500,375,ptyas mucosa,0,95,483,207,11
4,11301103_jpg.rf.7d0205f8d5e7d886d506cdaa0b02b7...,500,333,ahaetulla prasina,104,135,410,232,0
...,...,...,...,...,...,...,...,...,...
285,212851992_jpeg.rf.36f4d452a4981fc25d3f634df6ea...,500,201,ptyas korros,112,34,463,159,10
286,7453358_jpeg.rf.1412984b8963cc8e760efcd0096ad6...,500,333,bungarus fasciatus,81,163,320,251,3
287,205717014_jpeg.rf.53040dc10cc2942808d992177354...,500,375,psammodynastes pulverulentus,114,143,389,336,9
288,250193078_jpeg.rf.831a4a4e5a1adc3661b0b3237b75...,459,500,trimeresurus purpureomaculatus,0,12,428,482,13
289,158159739_jpg.rf.a07aef9f5697fb38a563e7d8c6eb6...,500,333,ptyas korros,93,111,393,247,10

In [27]:
# Verify the saved file
check_df = pd.read_csv('data/Processed_Images/Processed_test_annotations.csv')
print(check_df.head())

                                            filename  width  height  \
0  100844199_jpeg.rf.8663ed9382261d114f4f924308aa...    375     500
1  102866274_jpg.rf.afe5c17f98908bcaeaf3462adf4bb...    500     364
2  100844209_jpeg.rf.d4645d8cf8e9c0edfba87902a5a9...    375     500
3  100346824_jpeg.rf.37cdc3e14cb9f0f1a770d8bb470a...    500     375
4  11301103_jpg.rf.7d0205f8d5e7d886d506cdaa0b02b7...    500     333

                 class  xmin  ymin  xmax  ymax  Label
0   chrysopelea ornata   105     0   313   356      4
1  dendrelaphis pictus   183   114   500   263      6
2   chrysopelea ornata   126    84   218   372      4
3         ptyas mucosa     0    95   483   207     11
4    ahaetulla prasina   104   135   410   232      0

In [20]:
analyze_test_data()

Images to copy: 290

Copied : 0
Skipped: 290
Missing: 0
data/Processed_Images/Processed_test\_annotations.csv already exists. Skipping save.

## Validation Data

In [37]:
SOURCE_FOLDER = r"data/raw/valid"
CSV_FILE = os.path.join(SOURCE_FOLDER, "_annotations.csv")
DEST_FOLDER = r"data/Processed_Images/Processed_valid"

In [23]:
def analyze_valid_data():
    process_valid = pd.read_csv(CSV_FILE)
    
    # Normalize class names
    process_valid["class"] = (
        process_valid["class"]
            .str.strip()
            .str.lower()
    )
    # Handle synonyms
    process_valid["class"] = process_valid["class"].replace({
        "fowlea piscator": "xenochrophis piscator",
        "hebius stolatum": "amphiesma stolatum"
    })
    
    # Keep only target species
    filtered = process_valid[process_valid["class"].isin(TARGET_SPECIES)]

    # Remove duplicate filenames
    filtered = filtered.drop_duplicates(subset="filename")

    print(f"Images to copy: {len(filtered)}")
    
    
    # ===========================
    # COPY IMAGES
    # ===========================

    copied = 0
    skipped = 0
    missing = []

    os.makedirs(DEST_FOLDER, exist_ok=True)

    for filename in filtered["filename"].drop_duplicates().tolist():
        src = os.path.join(SOURCE_FOLDER, filename)
        dst = os.path.join(DEST_FOLDER, filename)

        if not os.path.exists(src):
            missing.append(filename)
            continue

        if os.path.exists(dst):
            skipped += 1
            continue

        shutil.copy2(src, dst)
        copied += 1
        
    print(f"\nCopied : {copied}")
    print(f"Skipped: {skipped}")
    print(f"Missing: {len(missing)}")

    if missing:
        print("\nMissing files:")
        for m in missing[:10]:
            print(m)
            
            
    # ===========================
    # SAVE FILTERED ANNOTATIONS
    # ===========================

    output_csv = os.path.join(DEST_FOLDER, "_annotations.csv")

    if os.path.exists(output_csv):
        print(f"{output_csv} already exists. Skipping save.")
    else:
        filtered.to_csv(output_csv, index=False)
        print(f"Saved {output_csv}")

In [24]:
VALID_CSV = pd.read_csv("data/Processed_Images/Processed_valid\_annotations.csv")

classes = sorted(TEST_CSV["class"].unique()) # sorts them alphabetically.

class_to_idx = { # mapping integers {"cobra": 0, "python": 1, "viper": 2}
    cls: idx
    for idx, cls in enumerate(classes) # enumerate give pairs like (0, "cobra"), (1, "python")
}

idx_to_class = { # reverse {0: "cobra", 1: "python", 2: "viper"}
    idx: cls
    for cls, idx in class_to_idx.items() 
}

In [25]:
# creates a new column called Label
VALID_CSV["Label"] = VALID_CSV["class"].map(class_to_idx) #  applies the mapping to every value in the class column.
VALID_CSV.to_csv("data/Processed_Images/Processed_valid_annotations.csv", index=False)
VALID_CSV

,filename,width,height,class,xmin,ymin,xmax,ymax,Label
0,81111653_jpg.rf.6bd8d000fd7763bb21dbcb5a14920a...,500,281,chrysopelea ornata,270,0,370,224,4
1,154491210_jpeg.rf.3cb9b824d815ad9714df213147b9...,500,281,ophiophagus hannah,216,66,500,281,8
2,132760813_jpeg.rf.081511636ebf82cc55ec5f8988d7...,500,430,trimeresurus albolabris,75,108,428,349,12
3,21733834_jpg.rf.cb6c91941460e26652be91debcd043...,375,500,ahaetulla prasina,116,228,375,500,0
4,21886303_jpeg.rf.252764fb41afe1e8935799e3b8f77...,281,500,amphiesma stolatum,43,105,168,255,1
...,...,...,...,...,...,...,...,...,...
567,68343774_jpg.rf.0ca500c90a77a9c07772b15d117f14...,500,447,ptyas mucosa,1,91,500,447,11
568,6540193_jpeg.rf.03238d9c87413e84af985f9570ebb2...,500,333,ahaetulla prasina,108,70,500,231,0
569,78664453_jpg.rf.5e713ba0dc1542d7e8e895944a40f6...,500,375,amphiesma stolatum,0,179,332,296,1
570,71566209_jpeg.rf.e1565d9098aa421074201ec9755da...,375,500,bungarus fasciatus,88,102,303,500,3
571,7477251_jpeg.rf.8aa6c73a55fe0292e20f9a48f91bbd...,500,375,dendrelaphis pictus,145,0,283,245,6

In [26]:
analyze_valid_data()

Images to copy: 290

Copied : 0
Skipped: 290
Missing: 0
data/Processed_Images/Processed_test\_annotations.csv already exists. Skipping save.