In [22]:
import os
import pandas as pd
from PIL import Image, ImageDraw

In [ ]:
filtered_species = pd.read_csv("data/Filtered_Train/filtered_annotations.csv")

In [5]:
filtered_species.sample(5)

,filename,width,height,class,xmin,ymin,xmax,ymax,Label
5750,61933665_jpg.rf.21efc6eb0965c0d69c5b4e27ee5b95...,500.0,438.0,ptyas mucosa,67.0,60.0,424.0,389.0,11
3921,237352784_jpeg.rf.edd2b2e39b6f4341017c969b00db...,500.0,375.0,xenochrophis piscator,155.0,66.0,294.0,375.0,14
3553,217740490_jpg.rf.ff857196727645857e8762d64979d...,500.0,333.0,trimeresurus purpureomaculatus,117.0,102.0,299.0,254.0,13
4804,AUG19740312_jpeg.rf.ff9e7ff66e43c4a5a6265d3773...,374.0,500.0,daboia russelii,133.0,189.0,272.0,443.0,5
1914,168632214_jpeg.rf.cdb9da49ed6b322b50ffca1deb09...,500.0,500.0,ptyas korros,71.0,68.0,430.0,483.0,10

In [6]:
OUTPUT_DIR = "data/Processed_Train/images"

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("Folder created.")

Folder created.

In [35]:
# Input
IMAGE_FOLDER = "data/Filtered_Train"
OUTPUT_FOLDER = "data/Processed_Train/images"

In [37]:
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

processed_rows = []

PADDING = 0.15  # 10% padding

for _, row in filtered_species.iterrows():

    image_path = os.path.join(IMAGE_FOLDER, row["filename"])

    try:
        image = Image.open(image_path).convert("RGB")

        img_width, img_height = image.size

        xmin = int(row["xmin"])
        ymin = int(row["ymin"])
        xmax = int(row["xmax"])
        ymax = int(row["ymax"])

        box_width = xmax - xmin
        box_height = ymax - ymin

        pad_x = int(box_width * PADDING)
        pad_y = int(box_height * PADDING)

        xmin = max(0, xmin - pad_x)
        ymin = max(0, ymin - pad_y)
        xmax = min(img_width, xmax + pad_x)
        ymax = min(img_height, ymax + pad_y)

        cropped = image.crop((xmin, ymin, xmax, ymax))

        save_path = os.path.join(OUTPUT_FOLDER, row["filename"])
        cropped.save(save_path)

        processed_rows.append({
            "filename": row["filename"],
            "class": row["class"],
            "Label": row["Label"],
            "width": cropped.size[0],
            "height": cropped.size[1]
        })

    except Exception as e:
        print(f"Error: {row['filename']} -> {e}")

Error: 41909982_jpg.rf.47525d16a431a0c56efcfeabc504d2be.jpg -> cannot identify image file 'data/Filtered_Train\\41909982_jpg.rf.47525d16a431a0c56efcfeabc504d2be.jpg'

In [48]:
processed_annotations = pd.DataFrame(processed_rows)

processed_annotations.to_csv(
    "data/Processed_Train/processed_annotations.csv",
    index=False
)

print(f"Successfully processed {len(processed_annotations)} images.")

Successfully processed 6109 images.

In [49]:
processed_species = pd.read_csv("data/Processed_Train/processed_annotations.csv")

In [50]:
processed_species.sample(7)

,filename,class,Label,width,height
5071,219660494_jpg.rf.647655b4539c4234aac1be8e619cd...,psammodynastes pulverulentus,9,108,250
6039,161449844_jpg.rf.7e7bb2571ddab18e122ad4d7ccacf...,bungarus caeruleus,2,209,425
3182,112130025_jpeg.rf.294219a0baafb892b707332de35a...,dendrelaphis pictus,6,500,374
2657,54206638_jpeg.rf.e71cede4d4bc8c1baedceee21c3bb...,daboia russelii,5,279,281
4421,157289117_jpeg.rf.1f9ff199e30efe821a71fdcfcf6f...,daboia russelii,5,141,375
3715,121968659_jpeg.rf.a89bc8662e5b419c74a36948619f...,amphiesma stolatum,1,375,118
3436,83977004_jpg.rf.9bc22f7d2d1cff1c97de5b54376d25...,bungarus fasciatus,3,231,88

In [51]:
filtered_species.sample(7)

,filename,width,height,class,xmin,ymin,xmax,ymax,Label
4877,AUG233761657_jpeg.rf.ddfbcde1b7d5d320817fdf9d5...,500.0,281.0,bungarus caeruleus,58.0,111.0,500.0,193.0,2
5034,AUG212625418_jpeg.rf.0b287a37a2b4ac577e3b93be1...,500.0,309.0,daboia russelii,211.0,105.0,269.0,296.0,5
2720,244293460_jpeg.rf.9c40bfeed08d0c779220c1404e87...,375.0,500.0,naja naja,59.0,204.0,356.0,374.0,7
591,115059959_jpeg.rf.afa852b1c23e268e03833a3fc70f...,500.0,375.0,trimeresurus purpureomaculatus,121.0,0.0,437.0,318.0,13
1103,160687429_jpg.rf.b30cb77b56fc9bede4a6568ce57e6...,500.0,375.0,daboia russelii,76.0,0.0,382.0,313.0,5
4231,7476056_jpeg.rf.eaccab7b11f3534c1992d1a75f66d9...,500.0,373.0,ahaetulla prasina,63.0,0.0,399.0,331.0,0
2023,114294106_jpeg.rf.50a986970f670afb7ed4f3d977d0...,500.0,303.0,daboia russelii,219.0,0.0,369.0,303.0,5

In [53]:
print("Processed Images:", len(os.listdir("data/Processed_Train/images")))
print("CSV Rows:", len(processed_annotations))

Processed Images: 6109
CSV Rows: 6109